[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "npx prisma migrate deploy && echo '=== Starting Node ===' && node dist/index.js 2>&1"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
