[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "sh -c 'npx prisma migrate deploy 2>&1; npx tsx prisma/seed.ts 2>&1; node dist/index.js 2>&1'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
